apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: my-app-prod
nameSuffix: -prod

commonLabels:
  foo: bar

patchesStrategicMerge:
- deployment_replicas.yaml
- deployment_env.yaml
- deployment_volume.yaml

configMapGenerator:
  - name: app-config
    literals:
      - username=admin

secretGenerator:
  - name: credentials
    type: Opaque
    literals:
      - password=prod-password
  - name: certs
    files:
      - assets/ca.pem